/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activity.database2;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vezeveer
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    private Connection con;
    private Statement stmt;
    CardLayout cardLayout;
    DefaultTableModel tableModel;
    String setSex = "female";
    int jpgNum = 4;
    
    public Main() {
        initComponents();
        this.setTitle("Profile Archiver [Currently using PEOPLE table]");
        
        //Check whether the driver is installed
        try{
            Class.forName("org.apache.derby.jdbc.ClientDriver");
        }catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "Driver not found: " +
                    e.getMessage());
        }
        
        
        
        //Connect to the database
        String url = "jdbc:derby://localhost:1527/sampledb";
        try{
            con = DriverManager.getConnection(url, "nbuser", "nbuser");
            stmt = con.createStatement();
            
            //Check if table exists
            DatabaseMetaData dbm = con.getMetaData();
            // check if "people" table is there
            ResultSet tables = dbm.getTables(null, null, "PEOPLE", null);
            if (tables.next()) {
                // proceed\
                System.out.println("All goood....");
            }
            else {
                System.out.println("Creating Table...");
                String sql2 = "CREATE TABLE PEOPLE (ID INTEGER NOT NULL, FIRSTNAME VARCHAR(30), LASTNAME VARCHAR(30), CITY VARCHAR(30), STREET VARCHAR(50), AVATAR VARCHAR(15), PRIMARY KEY (ID))";
                stmt.executeUpdate(sql2);
                System.out.println("Created people table..."); 
            }
            
        } catch (java.sql.SQLException e) {
            System.out.println("EXception WAS: " + e);
            JOptionPane.showMessageDialog(null, 
                    "Connection couldn't be established to " + url);
        }
        
        cardLayout = (CardLayout)jpanelsCollection.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelsCollection = new javax.swing.JPanel();
        pnlWelcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlSearch = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cbSearchTag = new javax.swing.JComboBox<>();
        btnGoToProfile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        btnGoToUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        pnlCreate = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfFirstNameCreate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfLastNameCreate = new javax.swing.JTextField();
        tfCityCreate = new javax.swing.JTextField();
        tfStreetCreate = new javax.swing.JTextField();
        tfIDCreate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblAvatarCreate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPrevAvatar = new javax.swing.JButton();
        btnNextAvatar = new javax.swing.JButton();
        btnFemale = new javax.swing.JButton();
        btnMale = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnClearCreate = new javax.swing.JButton();
        pnlDelete = new javax.swing.JPanel();
        pnlUpdate = new javax.swing.JPanel();
        pnlAbout = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        pnlProfile = new javax.swing.JPanel();
        lblProfilePic = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfProfileID = new javax.swing.JTextField();
        tfProfileName = new javax.swing.JTextField();
        tfProfileStreet = new javax.swing.JTextField();
        tfProfileCity = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemHome = new javax.swing.JMenuItem();
        menuItemCreate = new javax.swing.JMenuItem();
        menuItemSearch = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(512, 512));
        setSize(new java.awt.Dimension(512, 512));

        jpanelsCollection.setPreferredSize(new java.awt.Dimension(512, 512));
        jpanelsCollection.setLayout(new java.awt.CardLayout());

        pnlWelcome.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/avatarwelcom.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpanelsCollection.add(pnlWelcome, "pnlWelcome");

        pnlSearch.setBackground(new java.awt.Color(255, 153, 153));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cbSearchTag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Name", "ID", "Last Name", "City", "Street" }));

        btnGoToProfile.setText("Go to profile");
        btnGoToProfile.setEnabled(false);
        btnGoToProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToProfileActionPerformed(evt);
            }
        });

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "City", "Street", "Avatar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSearch);
        tblSearch.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblSearch.getColumnModel().getColumnCount() > 0) {
            tblSearch.getColumnModel().getColumn(0).setResizable(false);
            tblSearch.getColumnModel().getColumn(1).setResizable(false);
            tblSearch.getColumnModel().getColumn(2).setResizable(false);
            tblSearch.getColumnModel().getColumn(3).setResizable(false);
            tblSearch.getColumnModel().getColumn(4).setResizable(false);
            tblSearch.getColumnModel().getColumn(5).setResizable(false);
        }

        btnGoToUpdate.setText("Update profile");
        btnGoToUpdate.setEnabled(false);
        btnGoToUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoToUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnShowAll.setText("Show All Available");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGoToProfile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGoToUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbSearchTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShowAll)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(cbSearchTag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoToProfile)
                    .addComponent(btnGoToUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpanelsCollection.add(pnlSearch, "pnlSearch");

        pnlCreate.setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Create new person"));

        jLabel8.setText("First Name:");

        jLabel9.setText("Last Name:");

        jLabel10.setText("Street:");

        jLabel11.setText("City:");

        jLabel12.setText("ID:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfIDCreate)
                    .addComponent(tfFirstNameCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(tfLastNameCreate)
                    .addComponent(tfCityCreate)
                    .addComponent(tfStreetCreate))
                .addGap(69, 69, 69))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIDCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfFirstNameCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfLastNameCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfCityCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfStreetCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblAvatarCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fem4.jpg"))); // NOI18N

        jLabel2.setText("  Avatar");
        jLabel2.setToolTipText("");

        btnPrevAvatar.setText("<");
        btnPrevAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevAvatarActionPerformed(evt);
            }
        });

        btnNextAvatar.setText(">");
        btnNextAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextAvatarActionPerformed(evt);
            }
        });

        btnFemale.setText("F");
        btnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemaleActionPerformed(evt);
            }
        });

        btnMale.setText("M");
        btnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaleActionPerformed(evt);
            }
        });

        jLabel3.setText("Sex");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrevAvatar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNextAvatar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblAvatarCreate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(btnMale)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevAvatar)
                    .addComponent(jLabel2)
                    .addComponent(btnNextAvatar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvatarCreate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFemale)
                    .addComponent(btnMale)
                    .addComponent(jLabel3))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClearCreate.setText("Clear");
        btnClearCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClearCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClearCreate))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCreateLayout = new javax.swing.GroupLayout(pnlCreate);
        pnlCreate.setLayout(pnlCreateLayout);
        pnlCreateLayout.setHorizontalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCreateLayout.setVerticalGroup(
            pnlCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpanelsCollection.add(pnlCreate, "pnlCreate");

        javax.swing.GroupLayout pnlDeleteLayout = new javax.swing.GroupLayout(pnlDelete);
        pnlDelete.setLayout(pnlDeleteLayout);
        pnlDeleteLayout.setHorizontalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        pnlDeleteLayout.setVerticalGroup(
            pnlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jpanelsCollection.add(pnlDelete, "pnlDelete");

        javax.swing.GroupLayout pnlUpdateLayout = new javax.swing.GroupLayout(pnlUpdate);
        pnlUpdate.setLayout(pnlUpdateLayout);
        pnlUpdateLayout.setHorizontalGroup(
            pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        pnlUpdateLayout.setVerticalGroup(
            pnlUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jpanelsCollection.add(pnlUpdate, "pnlUpdate");

        jTextPane1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextPane1.setText("Programmer: Valdueza, Emmanuel\n\nDesigned by: Same person\n\nDate of working build: June 12th 2021\n\nProgram summary: Allows user to create a database of people that the user can easily look up.");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout pnlAboutLayout = new javax.swing.GroupLayout(pnlAbout);
        pnlAbout.setLayout(pnlAboutLayout);
        pnlAboutLayout.setHorizontalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        pnlAboutLayout.setVerticalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jpanelsCollection.add(pnlAbout, "pnlAbout");

        pnlProfile.setBackground(new java.awt.Color(0, 204, 204));

        lblProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fem4.jpg"))); // NOI18N
        lblProfilePic.setText("jLabel2");

        jLabel4.setText("ID:");

        jLabel5.setText("Name:");

        jLabel6.setText("Street:");

        jLabel7.setText("City:");

        tfProfileID.setEditable(false);
        tfProfileID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfProfileIDActionPerformed(evt);
            }
        });

        tfProfileName.setEditable(false);

        tfProfileStreet.setEditable(false);

        tfProfileCity.setEditable(false);

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlProfileLayout.createSequentialGroup()
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfProfileID)
                            .addComponent(tfProfileName)
                            .addComponent(tfProfileStreet)
                            .addComponent(tfProfileCity, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblProfilePic)
                .addGap(34, 34, 34)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfProfileID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfProfileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfProfileStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfProfileCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jpanelsCollection.add(pnlProfile, "pnlProfile");

        getContentPane().add(jpanelsCollection, java.awt.BorderLayout.CENTER);

        menuFile.setText("File");

        menuItemHome.setText("Home");
        menuItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHomeActionPerformed(evt);
            }
        });
        menuFile.add(menuItemHome);

        menuItemCreate.setText("Create");
        menuItemCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateActionPerformed(evt);
            }
        });
        menuFile.add(menuItemCreate);

        menuItemSearch.setText("Search");
        menuItemSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSearchActionPerformed(evt);
            }
        });
        menuFile.add(menuItemSearch);

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        jMenuBar1.add(menuFile);

        menuEdit.setText("More");

        jMenuItem1.setText("Help");
        menuEdit.add(jMenuItem1);

        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemAbout);

        jMenuBar1.add(menuEdit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSearchActionPerformed
        cardLayout.show(jpanelsCollection, "pnlSearch");
    }//GEN-LAST:event_menuItemSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        //Reset list
        if(tableModel != null)
            tableModel.setRowCount(0);
        
        boolean idSelected = false;
        String searchTag = "firstname";
        
        //Check if ID field is empty
        String fName = tfSearch.getText();
        if(fName.isEmpty()){
            JOptionPane.showMessageDialog(this, "field cannot be empty");
            return;
        }
        
        switch(cbSearchTag.getSelectedItem().toString()){
            case "ID": 
                searchTag = "id";
                idSelected = true;
                try{
                    Integer.parseInt(fName);
                } catch (Exception e){
                    JOptionPane.showMessageDialog(this, "ID must be a number");
                    return;
                }
                break;
            case "First Name": searchTag = "firstname"; break;
            case "Last Name": searchTag = "lastname"; break;
            case "City": searchTag = "city"; break;
            case "Street": searchTag = "street"; break;
        }
        
        try {
            ResultSet rs = stmt.executeQuery("select * from PEOPLE where " +
                    searchTag  + (idSelected ? 
                            ("="+fName)
                            :
                            (" LIKE '" + fName +"%'")
                            ));
            
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "No Record Found!");
                btnGoToProfile.setEnabled(false);
                btnGoToUpdate.setEnabled(false);
                btnDelete.setEnabled(false);
            } else {
                do{
                    
                    tableModel = (DefaultTableModel) tblSearch.getModel();
                    tableModel.insertRow(tableModel.getRowCount(), new Object[]{
                            Integer.parseInt(rs.getString("id")),
                            rs.getString("firstname"),
                            rs.getString("lastname"),
                            rs.getString("city"),
                            rs.getString("street"),
                            rs.getString("avatar")
                    });
                }while(rs.next());
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnGoToProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToProfileActionPerformed
        
            lblProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+tblSearch.getValueAt(tblSearch.getSelectedRow(), 5).toString()+".jpg")));
            tfProfileName.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 1) + " " + tblSearch.getValueAt(tblSearch.getSelectedRow(), 2));
            tfProfileID.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 0).toString());
            tfProfileCity.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 3).toString());
            tfProfileStreet.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 4).toString());
        
            cardLayout.show(jpanelsCollection, "pnlProfile");
    }//GEN-LAST:event_btnGoToProfileActionPerformed

    private void tblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchMouseClicked
        btnGoToProfile.setEnabled(true);
        btnGoToUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblSearchMouseClicked

    private void tfProfileIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfProfileIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfProfileIDActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        try {
            //CLOSE Statement and Connection objects to release resources
            stmt.close();
            con.close();
            System.exit(0);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateActionPerformed
        
        cardLayout.show(jpanelsCollection, "pnlCreate");
        
    }//GEN-LAST:event_menuItemCreateActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        cardLayout.show(jpanelsCollection, "pnlAbout");
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void btnNextAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextAvatarActionPerformed
        String sx = "fem";
        if(setSex != "female"){
            sx = "mal";
        }
        if(jpgNum == 5){
                jpgNum = 0;
        }
        jpgNum++;
        lblAvatarCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+sx+jpgNum+".jpg")));
        
        
    }//GEN-LAST:event_btnNextAvatarActionPerformed

    private void btnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaleActionPerformed
        setSex = "male";
        lblAvatarCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mal"+jpgNum+".jpg")));
    }//GEN-LAST:event_btnMaleActionPerformed

    private void btnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemaleActionPerformed
        setSex = "female";
        lblAvatarCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fem"+jpgNum+".jpg")));
    }//GEN-LAST:event_btnFemaleActionPerformed

    private void btnPrevAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevAvatarActionPerformed
        String sx = "fem";
        if(setSex != "female"){
            sx = "mal";
        }
        if(jpgNum == 1){
            jpgNum = 5;
        } else {
            jpgNum--;
        }
        lblAvatarCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+sx+jpgNum+".jpg")));
        
    }//GEN-LAST:event_btnPrevAvatarActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        try{
            Integer.parseInt(tfIDCreate.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "ID must be a number");
            return;
        }
        
        try {
            String id = tfIDCreate.getText();
            String lastName = tfLastNameCreate.getText();
            String firstName = tfFirstNameCreate.getText();
            String street = tfStreetCreate.getText();
            String city = tfCityCreate.getText();
            String avatar = lblAvatarCreate.getIcon().toString();
            
            avatar = avatar.substring(avatar.length()-8, avatar.length()-4);
            
            if (id.isEmpty() || lastName.isEmpty() || firstName.isEmpty()
                    || street.isEmpty() || city.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill up all fields");
                return;
            }
            
            
            
            ResultSet rs = null;
            rs = stmt.executeQuery("select * from PEOPLE where id = " + id);
            
            if(!rs.next()){
                String sq1 = "insert into PEOPLE (id, firstname, lastname, "+
                        "city, street, avatar) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement statement = con.prepareStatement(sq1);
                statement.setString(1, id);
                statement.setString(2, firstName);
                statement.setString(3, lastName);
                statement.setString(4, city);
                statement.setString(5, street);
                statement.setString(6, avatar);
                
                System.out.println("Executing...");
                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0){
                    JOptionPane.showMessageDialog(this, "Record added");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnGoToUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoToUpdateActionPerformed
        
        lblAvatarCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+tblSearch.getValueAt(tblSearch.getSelectedRow(), 5).toString()+".jpg")));
        tfFirstNameCreate.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 1).toString());
        tfLastNameCreate.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 2).toString());
        tfIDCreate.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 0).toString());
        tfCityCreate.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 3).toString());
        tfStreetCreate.setText(tblSearch.getValueAt(tblSearch.getSelectedRow(), 4).toString());
        
        cardLayout.show(jpanelsCollection, "pnlCreate");
    }//GEN-LAST:event_btnGoToUpdateActionPerformed

    private void btnClearCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCreateActionPerformed
        
        tfFirstNameCreate.setText("");
        tfLastNameCreate.setText("");
        tfIDCreate.setText("");
        tfCityCreate.setText("");
        tfStreetCreate.setText("");
    }//GEN-LAST:event_btnClearCreateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String id = tblSearch.getValueAt(tblSearch.getSelectedRow(), 0).toString();
            if(id.isEmpty()){
                JOptionPane.showMessageDialog(this, "ID field seems to be missing!");
                return;
            }
            String sql = "delete from PEOPLE where id=?";
            PreparedStatement statement;
            statement = con.prepareStatement(sql);
            statement.setString(1, id);
            int rowsDeleted = statement.executeUpdate();
            if(rowsDeleted > 0){
                JOptionPane.showMessageDialog(this, "Record deleted!!");
                if(tableModel != null)
                    tableModel.setRowCount(0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        //Reset list
        if(tableModel != null)
            tableModel.setRowCount(0);
        
        boolean idSelected = false;
        
        try {
            ResultSet rs = stmt.executeQuery("select * from PEOPLE");
            
            if(!rs.next()){
                JOptionPane.showMessageDialog(this, "There are no records in the database!");
                btnGoToProfile.setEnabled(false);
                btnGoToUpdate.setEnabled(false);
                btnDelete.setEnabled(false);
            } else {
                do{
                    tableModel = (DefaultTableModel) tblSearch.getModel();
                    tableModel.insertRow(tableModel.getRowCount(), new Object[]{
                            Integer.parseInt(rs.getString("id")),
                            rs.getString("firstname"),
                            rs.getString("lastname"),
                            rs.getString("city"),
                            rs.getString("street"),
                            rs.getString("avatar")
                    });
                }while(rs.next());
            }
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void menuItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHomeActionPerformed
        cardLayout.show(jpanelsCollection, "pnlWelcome");
    }//GEN-LAST:event_menuItemHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFemale;
    private javax.swing.JButton btnGoToProfile;
    private javax.swing.JButton btnGoToUpdate;
    private javax.swing.JButton btnMale;
    private javax.swing.JButton btnNextAvatar;
    private javax.swing.JButton btnPrevAvatar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbSearchTag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel jpanelsCollection;
    private javax.swing.JLabel lblAvatarCreate;
    private javax.swing.JLabel lblProfilePic;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemCreate;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemHome;
    private javax.swing.JMenuItem menuItemSearch;
    private javax.swing.JPanel pnlAbout;
    private javax.swing.JPanel pnlCreate;
    private javax.swing.JPanel pnlDelete;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JPanel pnlUpdate;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField tfCityCreate;
    private javax.swing.JTextField tfFirstNameCreate;
    private javax.swing.JTextField tfIDCreate;
    private javax.swing.JTextField tfLastNameCreate;
    private javax.swing.JTextField tfProfileCity;
    private javax.swing.JTextField tfProfileID;
    private javax.swing.JTextField tfProfileName;
    private javax.swing.JTextField tfProfileStreet;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfStreetCreate;
    // End of variables declaration//GEN-END:variables
}
